### ISSUE TITLE
Use flat types when extracting data from simulation

### ISSUE THREAD

**Issue by vmchale** [bittide/bittide-hardware#120]
Right now, we are able to simulate, but it uses a significant amount of RAM (>1GB). We should pass flat types (i.e. `Word`, `Int`, `(# ... #)` over `Natural`, `Integer`, `( ... )`) to matplotlib.

**Comment by martijnbastiaan** [comment]
> Right now, we are able to simulate, but it uses a significant amount of RAM (>1GB).

This turned out to be a space leak. Fixed by https://github.com/bittide/bittide-hardware/pull/181.
