### ISSUE TITLE
Add boot stage 1: fill elastic buffers, stabilize elastic buffers

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#125]
Related, now closed issue: https://github.com/google-research/bittide/issues/42.

As we've seen in simulations, buffer occupancies can decrease/increase arbitrarily while waiting for a system to become stable. For example, a system with "many" nodes has produced the following plot in the past:

![Screenshot from 2022-09-12 21-22-10](https://user-images.githubusercontent.com/5658854/189738122-31b49c99-f63b-4990-85d4-f57bc12e9921.png)

The problem is that larger systems would need larger FIFOs in order to function. This is unacceptable, as Bittide systems can grow arbitrarily large.

To solve this, a single node (with many elastic buffers) should follow roughly to following steps:

* Track mode:
  1. Collect all "stable" and "{under,over}flow" signals from the elastic buffers.
  2. If under/overflow: reset all elastic buffers and **clock control state**. Return to (1).
  3. If not all stable: return to (1).
 
* Stable mode:
  1. Monitor {under,over}flow. Export sticky version of these signals.

This algorithm works, as long as the individual steps always move closer to the ideal situation. Note that, while in boot mode any restrictions to the clock modifier board do not apply.

**Comment by lmbollen** [comment]
I created #217 as concept solution for this issue

**Comment by martijnbastiaan** [comment]
This has been fixed by [Sanjay's reframing approach](https://github.com/bittide/bittide-hardware/pull/279) combined with ["infinite" counters](https://github.com/bittide/bittide-hardware/pull/289).
