### ISSUE TITLE
Implement clock control test for CI.

### ISSUE THREAD

**Issue by lmbollen** [bittide/bittide-hardware#162]
We need a test that we can run on CI that verifies whether the clock control algorithm component stabilizes the clock.

I propose we extend the existing simulation interface with something along the lines of:
`sim check <topology> <steps> <points>`

This command should check whether simulation meets some stability criteria and dump the plots.

This criteria could look like:
`All clocks must remain within n ppm of the average at the end of the simulation`
 But maybe a good starting criteria would be .
`All clocks must remain within n ppm of the average after m cycles`

We have to make sure that this test works on CI, so it has to return `exitcode 1` if the test fails.

**Comment by kleinreact** [comment]
Implemented with #245.
