### ISSUE TITLE
Shake inconsistent rebuild behaviour due to relative pathing

### ISSUE THREAD

**Issue by lmbollen** [bittide/bittide-hardware#165]
While adding components to `bittide-instances` I noticed that shake's rebuild behaviour depends on your current path.
The rebuild behavior depends on the `dist-newstyle` directory in your current path, while it `dist-newstyle` is actually located in the project folder (where `cabal.project` is located).

We should change the implementation to locate the `cabal.project` file and depend on the `dist-newstyle` in that directory.

**Comment by lmbollen** [comment]
@martijnbastiaan PTAL

**Comment by martijnbastiaan** [comment]
Agreed, this is an issue. These lines need to change:

https://github.com/bittide/bittide-hardware/blob/4b57c30bacfdfd678f45e87ba651c31f90ed8bf6/bittide-instances/bin/Shake.hs#L112

https://github.com/bittide/bittide-hardware/blob/4b57c30bacfdfd678f45e87ba651c31f90ed8bf6/bittide-instances/bin/Shake.hs#L26-L27
