### ISSUE TITLE
Add clock board control state machinery

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#203]

**Comment by martijnbastiaan** [comment]
Updates:

 * We've got a core that can read/write registers over SPI to the Si539x boards.
 * We can generate useful configurations (clock enables / frequencies / ANYTHING)

**Comment by lmbollen** [comment]
Updates:
* Control state machinery now waits for the chip to be active (modulo minor bugs)
* We can now FINC / FDEC over SPI.

**Comment by lmbollen** [comment]
Superseded by #209

**Comment by martijnbastiaan** [comment]
> https://github.com/bittide/bittide-hardware/pull/215 solves this

It does! Let's close this issue.
