### ISSUE TITLE
Get transceivers to work

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#204]
For M3:

- [X] Black box for 1 channel
- [ ] Investigate whether we can instantiate multiple 1-channel black boxes or whether the blackbox needs to support multiple channels in one instantiation
- [x] Port PRBS tests to Clash
  - [X] Generator
  - [X] Receiver/checker
- [ ] Write initialization/reset state machine (PRBSs currently sometimes fail)

Optional for M3:
- [ ] Write circuit that (smartly) muxes between PRBS data and user data

**Comment by martijnbastiaan** [comment]
Updates:

 * Loopback link up with SMA cables @ 1 gbit/s (but we want SFP)

Next steps:

 * Bump to 10 gbit/s
 * Move to SFP / Direct Attach

**Comment by lmbollen** [comment]
Updates:
* We can hook up two FPGAs to each other via SFP and recover clocks from this.
* We can hook up the recovered clock to an elastic buffer and use callisto to synchronize these clocks.

**Comment by martijnbastiaan** [comment]
Updates:

 * 10 gbit/s is working
 * Fiber + DAC works

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/bittide/bittide-hardware/pull/306
