### ISSUE TITLE
Simplify TemplateHaskell infrastructure

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#207]

**Comment by kleinreact** [comment]
Implemented with #226.

`Bittide.Topology.TH` is still part of `elastic-buffer-sim`, but the module is not used anymore. Everything generated there is now part of `Bittide.Topology`. I kept `Bittide.Topology.TH` for easy comparison of both variants for the moment. If the PR review is sucessful, then `Bittide.Topology.TH` should be removed.
