### ISSUE TITLE
Make link configuration dynamic in Callisto

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#224]
We're currently looking into populating a mining rig with FPGAs and clock multipliers to lay the foundations for a clock control experimentation platform. Ideally, experimenting with it would be hooked up to GitHub Actions. To get some reasonable test turnaround time, we don't want to synthesize over-and-over again. Thus, it would be nice to be able to configure topologies (i.e., link enable/disable) at runtime.

Related: 

 * https://github.com/bittide/bittide-hardware/issues/207. Changing the type signature of Callisto will entail many changes in the `TemplateHaskell`. The proposed method would allow us to get rid of hardcoded topologies, eliminating the need for `TemplateHaskell` in the first place.
 * https://github.com/bittide/bittide-hardware/issues/208. More aggressive caching would eliminate a lot of re-synthesis.

**Comment by kleinreact** [comment]
Implemented with #226
