### ISSUE TITLE
Add VIO wrapper to `clash-cores`

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#238]
Part of https://github.com/bittide/bittide-hardware/issues/225. A VIO wrapper would allow us to control tests running on FPGA boards. See: https://www.xilinx.com/products/intellectual-property/vio.html.

**Comment by kleinreact** [comment]
See this [Draft PR](https://github.com/clash-lang/clash-compiler/pull/2422) for the current status.
