### ISSUE TITLE
Change Haxioms to not use `unsafeCoerce (Dict ())`

### ISSUE THREAD

**Issue by lmbollen** [bittide/bittide-hardware#241]
Using `unsafeCoerce` on `Dict ()` sometimes results in free variables. This can fixed by replacing unit `()` in `Dict ()` with something tangible, such as the relevant constraint.

**Comment by martijnbastiaan** [comment]
Related: https://github.com/clash-lang/clash-compiler/issues/2376

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/bittide/bittide-hardware/pull/297
