### ISSUE TITLE
Allow multiple VIOs in hardware tests

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#350]
As of https://github.com/clash-lang/clash-compiler/pull/2524 we can set VIO instance names. Ideally, CI would ignore all VIOs but a single "test control" one.

TODO:

- [x] Pick name
- [x] Change tests to instantiate VIOs with specific name
- [x] Update TCL to detect VIO with this specific name

**Comment by martijnbastiaan** [comment]
This has been done right @hiddemoll? Could you link to the specific PR and close this issue?

**Comment by hiddemoll** [comment]
Solved by #387
