### ISSUE TITLE
Add custom exit codes to hardware-in-the-loop tests

### ISSUE THREAD

**Issue by hiddemoll** [bittide/bittide-hardware#390]
Adding different exit codes allows for other failure modes. This way, we can add `shouldfail` tests for hardware-in-the-loop tests, which must fail in a specific way. Example exit codes:
- wrong probe config
- test timeout
- test failed

**Comment by martijnbastiaan** [comment]
Superseeded by https://github.com/bittide/bittide-hardware/pull/536
