### ISSUE TITLE
Improve and investigate clock control hardware plots

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#412]
Though we currently produce plots for clock control on the boards, we:

1. We don't use intuitive units (i.e., we should use PPM)
2. The local timestamps are currently limited to 32 bits due to the limits and necessity of the CDC Gray. This causes overflows that are visible within the plots, but which can be avoided by only reporting the cycles since the last capture instead.
3. Due to the size limitations of 3, it might be useful to generate a capture on a regular interval, even if the clock remains stable. This offers a more robust plot for the elastic buffers and allows to bound the number of cycles between two captures.
4. The bit sizes of the local and global time stamps are chosen arbitrarily. With the adaption of 4 they can be reduced substantially saving memory for the dumps.
5. The bit sizes of the dumped elastic buffer bounds can be also reduced via only reporting the difference against the last capture. A smaller bound needs to estimated for that, which should work most of the time. If it still gets exceeded in some cases we can just trigger a capture to reset it to zero in that case.
6. We should produce plots in some "baseline" scenarios and see if they match our expectations. This should give us much more confidence that what we're plotting is correct.

**Comment by kleinreact** [comment]
All except the last enhancement are covered by #415.
