### ISSUE TITLE
Synthesis fails on missing constraint file

### ISSUE THREAD

**Issue by kleinreact** [bittide/bittide-hardware#419]
Nightlies fail to synthesize `fullMeshHwCcWithRiscvTest`, because some `fullMeshHwCcWithRiscvTest.xdc` is missing (see for example [#3098](https://github.com/bittide/bittide-hardware/actions/runs/6473742845/job/17577166131#step:9:163)).

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/bittide/bittide-hardware/pull/433
