### ISSUE TITLE
Clock Control Simulation Results

### ISSUE THREAD

**Issue by kleinreact** [bittide/bittide-hardware#487]
The purpose of this issue is to collect interesting clock control simulation results being generated during the nightly simulation tests. 

We already know that the waiting times may cause issues if not selected appropriately (cf. #450), but it is not always clear whether that is indeed the only issue. Therefore, we additionally collect some long term data of interesting examples (appearing from time to time due to the random selection of the simulation parameters). Simulation is deterministic and only depends on the selected parameters making it a perfect candidate for long-term observations. However, CI artifacts are are only stored temporally, which is why why we need to collect the interesting cases over here.

---

![image](https://github.com/bittide/bittide-hardware/assets/15340601/75c14c19-c115-436a-b374-fba1601cc4d7)
<details>
<summary>Configuration & Report &nbsp;&nbsp;&nbsp;<i>(click to expand)</i></summary>

```json
{
  "clockOffsets": [
    -215,
    -375,
    135,
    385
  ],
  "disableReframing": false,
  "jsonArgs": null,
  "maxStartupOffset": 2000,
  "outDir": "_build",
  "outMode": "pdf",
  "rusty": true,
  "simulationSamples": 1000,
  "simulationSteps": 120000000,
  "stabilityFrameSize": 15000000,
  "stabilityMargin": 8,
  "stable": false,
  "startupOffsets": [
    643,
    1633,
    1006,
    1343
  ],
  "stopAfterStable": 120000000,
  "stopWhenStable": false,
  "topology": {
    "graph": "line",
    "nodes": 4
  },
  "waitTime": 100000
}
```

[report.pdf](https://github.com/bittide/bittide-hardware/files/14753955/report.pdf)
</details>

---

![image](https://github.com/bittide/bittide-hardware/assets/15340601/56d013cd-1527-48e8-a4d5-29f2bcc4f01e)
<details>
<summary>Configuration & Report &nbsp;&nbsp;&nbsp;<i>(click to expand)</i></summary>

```json
{
  "clockOffsets": [
    -350,
    -480,
    495,
    365
  ],
  "disableReframing": false,
  "jsonArgs": null,
  "maxStartupOffset": 2000,
  "outDir": "_build",
  "outMode": "pdf",
  "rusty": true,
  "simulationSamples": 1000,
  "simulationSteps": 120000000,
  "stabilityFrameSize": 15000000,
  "stabilityMargin": 8,
  "stable": false,
  "startupOffsets": [
    344,
    1722,
    420,
    131
  ],
  "stopAfterStable": 120000000,
  "stopWhenStable": false,
  "topology": {
    "graph": "line",
    "nodes": 4
  },
  "waitTime": 100000
}
```
[report.pdf](https://github.com/bittide/bittide-hardware/files/14862443/report.pdf)
</details>

**Comment by martijnbastiaan** [comment]
Closed by https://github.com/bittide/bittide-hardware/pull/615
