### ISSUE TITLE
Implement fast/efficient execution deadlines in software

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#587]
We currently maintain two instances for clock control: hardware and software. We use the former because it both consistently and reliably hits a (maximum) clock control update frequency of 1 MHz. While the latter does what we want in practice (clock convergence), we don't have a good idea on how long it takes to do a single clock control update. I.e.:

![Untitled Diagram drawio(1)](https://github.com/user-attachments/assets/7ec6b454-c28f-47f8-b5f8-24984608c0c9)

We don't really mind fewer updates (say, 100 KHz) but the updates should be timed reliably to make sure we can make our theory match our practice. We currently do have some timing logic implemented in Rust (`firmware-support/bittide-sys/src/time.rs`) backed by a hardware component `bittide/src/Bittide/Wishbone.hs` => `timeWb` but this is too slow to reliably schedule microseconds.

We should investigate what is needed to set a reliable update rate. There is no one valid solution that comes to mind, but in the end we should have a solution that:

* Can reliably hit an update mark precise to say 100 KHz.
* Gives feedback in such a way that it is immediately noticeable if the mechanism fails / the computation between updates takes too long

Relevant code:

* `bittide/src/Bittide/Wishbone.hs` => `timeWb`
* `firmware-support/bittide-sys/src/time.rs`: HAL for timing component
* `firmware-support/bittide-sys/src/clock_control.rs`: HAL for FINC/FDEC buttons
* `firmware-support/bittide-sys/src/callisto.rs`: Implementation of clock control algorithm ("Callisto")

**Comment by leonschoorl** [comment]
I added some [measurement hardware](https://github.com/bittide/bittide-hardware/commit/9927aaebcbf373c78094679b1083d11883415ffb) and ran [a test](https://github.com/bittide/bittide-hardware/actions/runs/10600359274/job/29416763045).

With the current setup the period between clock updates fluctuates between 405 and 414 cycles @ 125MHz.
Except for some reason on node 2, where it fluctuates between 403 and 412 cycles.
So the update frequency is `125 MHz / 414 = 0.301 MHz` or 301 kHz.
And the period is `414 / 125 MHz = 3.31e-6 s` or 3.31 μs

**Comment by rslawson** [comment]
I didn't realise that this would get closed when even just one of the linked PRs got closed, oops.

**Comment by rslawson** [comment]
Oops, still not done with #654.
