### ISSUE TITLE
Investigate "discreteness" of clock plots

### ISSUE THREAD

**Issue by martijnbastiaan** [bittide/bittide-hardware#611]
If we look at any clock plot that starts of sufficiently closely to the convergence frequency, we can observe a certain "blockiness" or "discreteness" of the plots:

![Screenshot from 2024-08-21 10-14-17](https://github.com/user-attachments/assets/1bde4781-40ea-41bc-89af-91408c8262cc)

The step size corresponds to roughly 0.5 ppm, while the clock step size is 0.01 ppm (10 ppb). I don't think this is fundamental to our measurement method:

* We sample every 5 ms, or every 5×125_000_000 = 625_000_000 (ideal) clock cycles.
* 0.5 ppm is therefore 312.5 clock cycles
* 10 ppb is therefore 6.25 clock cycles

While I can see there might be some synchronization logic messing with the precision around ~10 ppb, I don't think 0.5 ppm should be a cut-off point. Perhaps a good first step would be to remove all the type juggling in https://github.com/bittide/bittide-hardware/issues/609 to get a good view on where all the conversions happen.

**Comment by martijnbastiaan** [comment]
Oh no, another case of _I'm off by 3 orders of magnitude_. The correct logic would be:

 * We sample every 20 ms, or every 20×125_000 = 2_500_000 (ideal) clock cycles, given a clock of 125 MHz.
 * 0.5 ppm is therefore 2.5 clock cycles
 * 10 ppb is therefore 0.025 clock cycles

And so, because the source data dances around -1,0,1 we _do_ expect "glitches" of ~0.5 ppm.

**Comment by hiddemoll** [comment]
Leaving this comment for future us.

To quote Martijn from Slack:
> The plot shows measured frequency vs "guessed" frequency. The former through measuring frequency "directly" by measuring how many cycles an fpga counted too many/too few compared to a reference clock. The latter by plotting where an fpga thinks it is based on the number of times it pressed FINC/FDEC.

![Image](https://github.com/user-attachments/assets/b68a2ab3-7263-4bf4-a45c-7b302dbfd968)

Martijn wondered why we only see 3 states in the measured frequency (black line); one measuring artifact up, zero, or down. In the previous comment Martijn says:
> We have two clock crossings, so we can expect ~4 clock cycles of uncertainty, or 1.6 ppm.

But it is actually 3 clock cycles of uncertainty. The clock domain crossings can fall either fall left-left, right-right, left-right or right-left, but the last two states have the same clock cycle uncertainty.

**Comment by martijnbastiaan** [comment]
Hmm, in other plots I _do_ see 4 values:

![Image](https://github.com/user-attachments/assets/8ad7fa6d-30c9-446c-9d69-0ecc92a46c31)

So I'm not entirely sure about the methodology (either way).
