### ISSUE TITLE
Add haskell function to program soft-core with openOCD and GDB

### ISSUE THREAD

**Issue by lmbollen** [bittide/bittide-hardware#648]
We currently have some functionality to start `gdb` and run a script that is located outside of the Haskell code. But it would be nice to at least have a reusable function to load a binary onto the FPGA.
This could simply be a function that starts openocd, starts gdb, programs the soft-core connected via JTAG and starts execution.

Currently the `adapter usb location` is hardcoded to `1-5.1:1`, in the `sipeed.tcl` script.
We need to be able to control this via haskell.

The location itself is a static USB path that points to the JTAG interface.
These paths can be shown using `lsbusb -t` where `1-5.1:1` means:
<pre>
/:  <b>Bus 01</b>.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/16p, 480M
    |__ <b>Port 5</b>: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 3: Dev 20, If 0, Class=Vendor Specific Class, Driver=, 12M
        |__ Port 3: Dev 20, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
        |__ Port 1: Dev 4, If 0, Class=Vendor Specific Class, Driver=, 12M
        |__ <b>Port 1</b>: Dev 4, <b>If 1</b>, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
        |__ Port 4: Dev 9, If 0, Class=Hub, Driver=hub/4p, 480M
            |__ Port 4: Dev 13, If 0, Class=Hub, Driver=hub/4p, 480M
                |__ Port 1: Dev 14, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
                |__ Port 1: Dev 14, If 0, Class=Vendor Specific Class, Driver=, 12M
                |__ Port 2: Dev 15, If 0, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
                |__ Port 2: Dev 15, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
            |__ Port 2: Dev 11, If 0, Class=Vendor Specific Class, Driver=, 12M
            |__ Port 2: Dev 11, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
            |__ Port 3: Dev 12, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
            |__ Port 3: Dev 12, If 0, Class=Vendor Specific Class, Driver=, 12M
            |__ Port 1: Dev 10, If 0, Class=Vendor Specific Class, Driver=, 12M
            |__ Port 1: Dev 10, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
        |__ Port 2: Dev 17, If 1, Class=Vendor Specific Class, Driver=ftdi_sio, 12M
        |__ Port 2: Dev 17, If 0, Class=Vendor Specific Class, Driver=, 12M
    |__ Port 7: Dev 3, If 2, Class=Mass Storage, Driver=usb-storage, 480M
    |__ Port 7: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 480M
    |__ Port 7: Dev 3, If 1, Class=Human Interface Device, Driver=usbhid, 480M
    |__ Port 9: Dev 5, If 0, Class=Hub, Driver=hub/4p, 480M
    |__ Port 11: Dev 7, If 0, Class=Human Interface Device, Driver=usbhid, 12M
</pre>

**Comment by martijnbastiaan** [comment]
Perhaps we could pass these in using environment variables? I.e., something like:

```
USB_DEVICE="1-5.1:1" gdb the_script.tcl
```

**Comment by lmbollen** [comment]
@martijnbastiaan How would we then open multiple jtag devices at once?

**Comment by martijnbastiaan** [comment]
We're currently using [`withCreateProcess`](https://hackage.haskell.org/package/process-1.6.25.0/docs/System-Process.html#v:withCreateProcess), which takes a [`CreateProcess`](https://hackage.haskell.org/package/process-1.6.25.0/docs/System-Process.html#t:CreateProcess). Each `CreateProcess` can pass its own environment variables ([`env`](https://hackage.haskell.org/package/process-1.6.25.0/docs/System-Process.html#v:env)). I.e., you would start OpenOCD multiple times, each with its own environment variable.

**Comment by lmbollen** [comment]
Ah interesting. Currently @hiddemoll has a working implementation, but that seems like a way simpler approach. You'll see the PR soon I think
