### ISSUE TITLE
Remove `Maybe` from `DataLink`

### ISSUE THREAD

**Issue by lmbollen** [bittide/bittide-hardware#662]
Currently the `DataLink` type used by the scatter unit and gather unit is:
```hs
-- | Either contains a @Just (BitVector frameWidth)@ or @Nothing@.
type DataLink frameWidth = Maybe (BitVector frameWidth)
```
But since all communication is scheduled ahead of time we don't need any flow control mechanisms at this level.
As a workaround we can apply `Just` to all `BitVector frameWidths` and use `fromMaybe 0` to strip them.

The scatter engines, gather engines, switch and their tests should be adjusted to reflect this change.

**Comment by martijnbastiaan** [comment]
Close by https://github.com/bittide/bittide-hardware/pull/679
